server:
  port: 8761
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
spring:
  application:
    name: eureka-server
#  server:
#    serviceUrl:
#      defaultZone: http://localhost:8761